name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Wednesday 7 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 7 * * 3'

env:
  TEST_BIGDATA: "https://bytesalad.stsci.edu/artifactory"

jobs:
  pep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 ci_watson --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools build "twine>=3.3"
        python -m build --sdist .
        twine check --strict dist/*

  basic_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[test,all]
    - name: Test
      run: pytest tests

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .[test,all]
    # --bigdata untestable due to Artifactory lockdown
    - name: Test
      run: pytest tests --slow --env=stable --basetemp=tests_output --junitxml results.xml

  devdep_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install git+https://github.com/astropy/astropy --no-deps
        python -m pip install -e .[test,all]
    # --bigdata untestable due to Artifactory lockdown
    - name: Test
      run: pytest tests --slow --basetemp=tests_output --junitxml results.xml
